Wayfinding/Models/IconDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class IconDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Wayfinding/Models/MapDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class MapDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public int Zoom { get; set; }
        public string Username { get; set; }
    }
}

Wayfinding/Models/MapListDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class MapListDto
    {
        public MapDto[] Maps { get; set; }
    }
}

Wayfinding/Models/NodeDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class NodeDto
    {
        public int Id { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
    }
}

Wayfinding/Models/NodesListDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class NodesListDto
    {
        public NodeDto[] Nodes { get; set; }
    }
}

Wayfinding/Models/POIDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class POIDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int NodeID { get; set; }
        public int Size { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public int Map { get; set; }
    }
}

Wayfinding/Models/POIsListDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class POIsListDto
    {
        public POIDto[] POIs { get; set; }
    }
}

Wayfinding/Models/RoadDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class RoadDto
    {
        public int Id { get; set; }
        public double Length { get; set; }
        public int StartNode { get; set; }
        public int EndNode { get; set; }
        public int Size { get; set; }
        public int Map { get; set; }
    }
}

Wayfinding/Models/RoadsListDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.Models
{
    public class RoadsListDto
    {
        public RoadDto[] Roads { get; set; }
    }
}

Wayfinding/ViewModels/AddMap.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class AddMap
    {
        public string Name { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public int Zoom { get; set; }
        public string Username { get; set; }
    }
}

Wayfinding/ViewModels/AddPoint.cs
using EntityModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class AddPoint
    {
        public string Name { get; set; }
        public int NodeID { get; set; }
        public int Size { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public int Map { get; set; }
    }
}

Wayfinding/ViewModels/AddRoad.cs
using EntityModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class AddRoad
    {
        public float Length { get; set; }
        public int StartNodeID { get; set; }
        public int EndNodeID { get; set; }
        public int Size { get; set; }
        //public Node[] Nodes { get; set; }
        public int Map { get; set; }
    }
}

Wayfinding/ViewModels/ChangeColor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class ChangeColor
    {
        public string Element { get; set; }
        public string Color { get; set; }
    }
}

Wayfinding/ViewModels/EditorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class EditorViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public int Zoom { get; set; }
    }
}

Wayfinding/ViewModels/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class Login
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Wayfinding/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class LoginViewModel
    {
        public string User { get; set; }
    }
}

Wayfinding/ViewModels/SignupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class SignupViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Wayfinding/ViewModels/UpdatePoint.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class UpdatePoint
    {
        public int ID { get; set; }
        public string Desc { get;  set; }
        public int? Size { get; set; }
    }
}

Wayfinding/ViewModels/UpdateRoad.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Wayfinding.ViewModels
{
    public class UpdateRoad
    {
        public int ID { get; set; }
        public float? NewLength { get; set; }
        public int? NewSize { get; set; }
    }
}

Wayfinding/Controllers/GetStartedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wayfinding.Controllers
{
    public class GetStartedController : Controller
    {
        // GET: GetStarted
        public ActionResult Index(String user)
        {
            return View("Index");
        }
    }
}

Wayfinding/Controllers/IconController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using EntityModels;
using Newtonsoft.Json;

namespace Wayfinding.Controllers
{
    public class IconController : Controller
    {
        [HttpPost]
        public ActionResult StoreIcon(HttpPostedFileBase FileUpload)
        {
            var database = new WayFindingUniBOEntities1();
            var icon = new EntityModels.Icon
            {
                Name = FileUpload.FileName.ToString().Replace(".svg", "")
            };

            database.Icon.Add(icon);
            database.SaveChanges();
            if (FileUpload != null && FileUpload.ContentLength > 0)
            {
                var fileName = Path.GetFileName(FileUpload.FileName);
                var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                FileUpload.SaveAs(path);
            }

            return RedirectToAction("Index", "GetStarted", new { uploaded = 1});
        }

    }
}

Wayfinding/Views/GetStarted/Index.cshtml
@using System.Web.Optimization
@using Wayfinding.ViewModels

@{
    Layout = null;
    int updated = HttpContext.Current.Request.QueryString["uploaded"].AsInt();
}

@model LoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
          integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
          crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
            integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
            crossorigin="">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        var User = document.URL.substr(document.URL.indexOf("=")+1);
    </script>
    <script src="~/Scripts/get-started.js"></script>
    <link rel="stylesheet" href="~/Content/get_start_style.css">
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    
</head>
<body>
    <div id="title">
        <img src="Content\WebImages\LilioIcon.png" alt="X">
    </div>
    <div id="choose">
        <!--- <button id="new">New</button>              -->
        <!--- <button id="load">Load</button>            -->
        <!--- <button id="upload_icon">New Icon</button> -->
        <!--- <button id="maps">Maps</button>            -->
        <div id="newmap">
            <h1>New Map</h1>
            <img src="Content\WebImages\newmap.svg" alt="X">
            <p>Create a map from scratch supported by our editor tools! </p>
        </div>
        <div id="maps">
            <h1>Maps</h1>
            <img src="Content\WebImages\maps.svg" alt="X">
            <p>Manage your maps and keep clean your database!</p>
        </div>
        <div id="settings">
            <h1>Settings</h1>
            <img src="Content\WebImages\settings.svg" alt="X">
            <p>Load and modify a map from the historicized!</p>
        </div>
    </div>
    <div id="managemaps">

    </div>
    <div id="settingspanel">
        <div id="settings">
            <div id="option1">
                <label for="circle">Node Color</label>
                <div class="color">
                    <button class="white"></button>
                    <button class="grey"></button>
                    <button class="blue"></button>
                    <button class="lightgreen"></button>
                    <button class="cyan"></button>
                    <button class="yellow"></button>
                    <button class="purple"></button>
                    <button class="orange"></button>
                </div>
            </div>
            <div id="option2">
                <label for="circleedge">Node Border Color</label>
                <div class="color">
                    <button class="white"></button>
                    <button class="grey"></button>
                    <button class="blue"></button>
                    <button class="lightgreen"></button>
                    <button class="cyan"></button>
                    <button class="yellow"></button>
                    <button class="purple"></button>
                    <button class="orange"></button>
                </div>
            </div>
            <div id="option3">
                <label for="Road">Road Color</label>
                <div class="color">
                    <button class="white"></button>
                    <button class="grey"></button>
                    <button class="blue"></button>
                    <button class="lightgreen"></button>
                    <button class="cyan"></button>
                    <button class="yellow"></button>
                    <button class="purple"></button>
                    <button class="orange"></button>
                </div>
            </div>
            <div id="option4">
                <label for="roadss">Road Selection Style Color</label>
                <div class="color">
                    <button class="white"></button>
                    <button class="grey"></button>
                    <button class="blue"></button>
                    <button class="lightgreen"></button>
                    <button class="cyan"></button>
                    <button class="yellow"></button>
                    <button class="purple"></button>
                    <button class="orange"></button>
                </div>
            </div>
            <div id="option5">
                <label for="circless">Node Selection Style Color</label>
                <div class="color">
                    <button class="white"></button>
                    <button class="grey"></button>
                    <button class="blue"></button>
                    <button class="lightgreen"></button>
                    <button class="cyan"></button>
                    <button class="yellow"></button>
                    <button class="purple"></button>
                    <button class="orange"></button>
                </div>
            </div>
            <button id="savechanges">Save Changes</button>
        </div>
        <div id="icons">
            <button id="add">
                Add Icon
                <img src="Content\WebImages\arrowdown.svg" alt="">
            </button>
            <div id="addicon">
                <!-- <form action="http://localhost/Wayfinding/Icon/StoreIcon">-->
                @using (Html.BeginForm("StoreIcon", "Icon", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <p><input id="add_icon_btn" type="file" name="FileUpload" /></p>
                    <!--<img id="toUpload" src="" />-->
                    <button id="ok">OK</button>
                }
            </div>
            <button id="remove">
                Remove Icon
                <img src="Content\WebImages\arrowdown.svg" alt="">
            </button>
            <div id="removeicon">
                <div id="allicons">

                </div>
                <div id="selection">
                    <button id="removeselected">Remove</button>
                    <button id="clearselection">Clear Selection</button>
                </div>
            </div>
        </div>

        <div id="settings">

        </div>
    </div>
    <div id="load_gif">
        <img src="~/Images/load_gif.gif" />
    </div>
    <!--
    <div id="add_icon">
         <form action="http://localhost/Wayfinding/Icon/StoreIcon">
        @using (Html.BeginForm("StoreIcon", "Icon", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <p><input id="add_icon_btn" type="file" name="FileUpload" /></p>
            <!--<img id="toUpload" src="" />-->
    <!-- <input type="submit" value="OK" />-->

}
<!---- </form>--->
    </div>
<div id="load_panel">
    <div id="select_map">
        <p>
            <label for="map_name">
                Choose a map :
                <select name="map" id="map_name"></select>
            </label>
        </p>
    </div>
    <div id="confirm">
        <button id="ok">OK</button>
    </div>
</div>
@if (updated == 1)
{
    <div>
        <p>Icona Caricata</p>
    </div>
}
</body>
</html>